---
- name: Download Play 2.1.4
  get_url: url=http://downloads.typesafe.com/play/2.1.4/play-2.1.4.zip
           dest=/tmp/play.zip

- name: Install unzip
  apt: update_cache=yes pkg=$item
  with_items:
  - zip
  - unzip

- name: Unzip Play
  shell: unzip /tmp/play.zip > /dev/null
         chdir=/tmp
         creates=/tmp/play-2.1.4

- name: Create /home/vagrant/bin
  file: path=/home/vagrant/bin
        state=directory
        owner=vagrant
        group=vagrant

- name: Copy Play
  shell: export DIR=/home/vagrant/bin/play-2.1.4; cp -R /tmp/play-2.1.4 $DIR && chown -R vagrant:vagrant $DIR
         creates=/home/vagrant/bin/play-2.1.4

- name: Check Play in PATH
  shell: grep -q '/home/vagrant/bin/play-2.1.4:$PATH' /home/vagrant/.bashrc
  register: play_in_path
  ignore_errors: yes

- name: Add Play to PATH
  shell: echo 'export PATH=/home/vagrant/bin/play-2.1.4:$PATH' >> /home/vagrant/.bashrc
  when: play_in_path|failed
