---
# the SBT installer needs curl
- name: Install curl
  apt: pkg=curl update_cache=yes

- name: Download SBT
  get_url: url=http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.13.0/sbt.deb
           dest=/tmp/sbt.deb

- name: Install SBT
  shell: dpkg -i /tmp/sbt.deb
