---
- hosts: development
  sudo: yes
  tasks:
  - name: check_ghc
    shell: "ghc --version | grep -q 7.6.3"
    ignore_errors: yes
    register: ghc_installed

  - include: "tasks/install-ghc.yml"
    when: ghc_installed|failed



- hosts: development
  sudo: yes
  sudo_user: vagrant
  tasks:
  - name: cabal check
    shell: "cabal --numeric-version | grep -q 1.18"
    ignore_errors: yes
    register: cabal_installed

  - include: "tasks/install-cabal.yml"
    when: cabal_installed|failed
