---
# all hosts
- include: "common/playbooks/elasticsearch/install.yml"
- include: "common/playbooks/tesseract/install.yml"

# dev hosts
- include: "dev-config/playbooks/common_tools/install.yml"
- include: "dev-config/playbooks/bash/configure.yml"
- include: "dev-config/playbooks/ghc/install.yml"
