---
- hosts: development
  sudo: yes
  sudo_user: ${gratte_user}
  tasks:
  - name: Pull from git
    git: repo=https://github.com/ostapneko/gratte-papier
         dest=/home/${gratte_user}/apps/gratte/workspace

  - name: Link to current workspace
    file: path=/home/${gratte_user}/apps/gratte/current state=link
          src=/home/${gratte_user}/apps/gratte/workspace

  - name: Install Coffeescript
    sudo_user: root
    apt: update_cache=yes pkg=coffeescript state=latest

  - name: Build project
    shell: make
           chdir=/home/${gratte_user}/apps/gratte/current

  - name: Start gratte-server
    sudo_user: root
    shell: status gratte-server | grep -q running || start gratte-server
